#!/usr/bin/groovy

// String SlackChannel = 'sdiego'
String JenkinsServer = "${env.JENKINS_URL}/job/${env.JOB_NAME}/${env.BUILD_ID}/console"

node (''){
    env.OCP_API_SERVER = "${env.OPENSHIFT_API_URL}"
    env.OCP_TOKEN = readFile('/var/run/secrets/kubernetes.io/serviceaccount/token').trim()
//    env.JENKINS_SERVER = "https://jenkins-demo-pipeline-sdiego.apps.d1.core.rht-labs.com/job/${env.JOB_NAME}/${env.BUILD_ID}/console"
}

node('') {
    stage('SCM Checkout')
    {
      checkout scm
    }

//    slackSend channel: SlackChannel, color: "#439FE0", message: "@channel - Build started. ${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME}"

    stage('Build Image') {
      sh "oc start-build ${env.APP_NAME} --from-dir=. --follow"
    }

    stage ('Security Scanning')
    {
      echo 'Security Scanning... please wait'
      sleep 3
    }

    stage ('Deploy to Dev') {
      sh "oc tag ${env.NAMESPACE_BUILD}/${env.APP_NAME}:latest ${env.NAMESPACE_DEV}/${env.APP_NAME}:latest"
    }

    stage ('Deploy to Test') {
      sh "oc tag ${env.NAMESPACE_DEV}/${env.APP_NAME}:latest ${env.NAMESPACE_TEST}/${env.APP_NAME}:latest"
    }

    stage ('Automated Tests')
    {
      echo 'Running automated tests.' 
      sleep 2
      echo 'All good here!'
    }

//    slackSend channel: SlackChannel, color: "#439FE0", message: "@jranoa - JOSH!! - the build needs your attention: ${env.JENKINS_SERVER}"

    stage ('Deploy to Production') {
      input "Promote Application to UAT?"
      sh "oc tag ${env.NAMESPACE_TEST}/${env.APP_NAME}:latest ${env.NAMESPACE_PROD}/${env.APP_NAME}:latest"
    }

//    slackSend channel: SlackChannel, color: "#00FF00", message: "@channel - SUCCESSFUL: New version is now in production!"
}
